- name: swe_agent

  _target_: uni_agent.agent_loop.UniAgentLoop
  concurrency: 64
  log_dir: /tmp/swebench_qwen3_coder
  mask_abnormal_exit_traj: false

  interaction:
    action_timeout: 300
    max_turns: 100

  env:
    deployment:
      type: openyuanrong
      command: /opt/swe-rex/bin/python /opt/swe-rex/bin/swerex-remote --host 0.0.0.0 --port {port} --auth-token {token}
      timeout: 600
      startup_timeout: 600
      swerex_runtime_image: swr.cn-east-3.myhuaweicloud.com/openyuanrong/swerex-runtime:1.4.0
      swerex_runtime_target: /opt/swe-rex
    env_variables:
      PIP_PROGRESS_BAR: "off"
      PIP_CACHE_DIR: "~/.cache/pip"
      PAGER: "cat"
      MANPAGER: "cat"
      LESS: "-R"
      TQDM_DISABLE: "1"
      GIT_PAGER: "cat"

  tool_parser: qwen3_coder

  tools:
    - name: str_replace_editor
    - name: execute_bash
    - name: submit

  reward:
    eval_timeout: 600
